
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: . #эта хуйня говорит что мы билдим наш образ из текущей директории
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py create_test_users && python manage.py runserver 0.0.0.0:8000" # Костыль: ждём 5 сек перед запуском сервера
      # sh -c "sleep 5" нужно для того что бы датабаза стартовала на 5 секунд раньше сервера и точно успевала прогрузится
      # потом запускается скрипт создания тестовых пользователей из custom_auth/management/commands/create_test_users.py 
      # ну а потом запускается сервер
    ports:
      - "8000:8000" # Пробрасываем порт 8000 из контейнера на хост
    depends_on: 
      - db # Зависимость от базы, но без healthcheck это просто порядок запуска 
      #TODO: add healthcheck

      
    environment: #takes variables from .env file
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - Debug=True
    volumes:
      # adding local directory to container
      - .:/app
    env_file:
      # specify env file
      - .env  
    develop: #this thing is needed to rebuild container on file changes
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore: #ignoring these directories and files 
            - .git/
            - __pycache__/
            - venv/
            - .idea/ #это для сергея, что бы у него докер не пересобирался от каждого изменения в .idea
            - logs/ #for future logs file that should be ignored 

volumes:
  postgres_data: 