
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=crypto_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=podikBezGari
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on: 
      - db
      #эта хуйня должна замедлять наш старт сервера, что бы
      #он стартовал не раньше старта датабазы что бы не выдал ошибку, но оно не работает
      #по этому там есть sh -c "sleep 5" (сервер ждёт 5 секунд до запуска что бы датабаза точно смогла прогрузится)
    environment:
      - DB_NAME=crypto_db
      - DB_USER=postgres
      - DB_PASSWORD=podikBezGari
      - DB_HOST=db
      - DB_PORT=5432
volumes:
  postgres_data: 