# Generated by Django 4.2 on 2025-03-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='allocation',
            new_name='quantity',
        ),
    ]
